version: '3.8'

services:
  frontend:
    image: node:20
    working_dir: /app
    container_name: react-chat-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    container_name: node-chat-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
    
      - JWT_SECRET=your_jwt_secret
      - PORT=5000

    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-chat-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-network

volumes:
  mongo-data:

networks:
  chat-network:
    driver: bridge
